---
title: "Constructs"
output: html_document
---

<style>
.column {
float: left;
width: 50%;
padding: 10px;
}

.row:after {
content: "";
display: table;
clear: both;
}

.mp {
font-weight: bold;
color: lightblue;
}

</style>



# Example Views {.tabset .tabset-fade}  
## One Construct Only {-}  

<div class="row">
<div class="column">
<input
type="text"
placeholder="Search"
/>

<ul style="border: 2px solid black">
<li>Demographics</li>
<li>Job Attitudes</li>
<li>Ageing and Work</li>
<li>Work Design
<ul>
<li>Job Demands</li>
<li>Job Constraints</li>
<li>Job Support</li>
<li>Job Autonomy
<ul>
<li style="background:AliceBlue;">job_aut1: My work allowed me to take initiative</li>
<li>job_aut2: I could make my own decisions</li>
<li>job_aut3: My work gave me great decision latitude</li>
</ul>
</li>

</ul>
</li>

</ul>


#### Selection

<div style="border: 2px solid black;"> job_aut1</div>  
#### Measured At
  
|      |                       |      |      |      |      |
|------|-----------------------|------|------|------|------|
| T1   |                       | T12  | T24  |      | T43  |
|      |                       | T13  | T25  |      | T44  |
|      | <strong>T2</strong>   | T14  | T26  |      | T45  |
|      | <strong>T3</strong>   | T15  | T27  |      | T46  |
|      | <strong>T4</strong>   | T16  | T28  |      | T47  |
|      | <strong>T5</strong>   | T17  | T29  | T36  | T48  |
|      | <strong>T6</strong>   | T18  | T30  | T37  | T49  |
|      | <strong>T7</strong>   | T19  | T31  | T38  | T50  |
|      | <strong>T8</strong>   | T20  | T32  | T39  | T51  |
|      | <strong>T9</strong>   | T21  | T33  | T40  | T52  |
|      | <strong>T10</strong>  | T22  | T34  | T41  | T53  |
|      | <strong>T11</strong>  | T23  | T35  | T42  | T54  |

Comment: one could select more and more items with "&" or "|" operators, indicating only observations where all/at least one of these items was measured. The table would then show, which measurement points would remain with this selection.


<div style="border: 2px solid black;">N = 1780, n = 7964</div>  


</div><!--First Column -->




<div class="column">
### Construct: Job Autonomy  

#### Original

Intro: Please think about the last 3 Months/4 Weeks  
Text: My work allowed me to take initiative  
Scale:  

- 1 = does not apply at all
- 2 = hardly applies
- ...
- 7 = fully applies

Citation: Morgeson, F. P., & Humphrey, S. E. (2006). The Work Design Questionnaire (WDQ): Developing and validating a comprehensive measure for assessing job design and the nature of work. Journal of Applied Psychology, 91(6), 1321 -1339. https://doi.org/10.1037/00219010.91.6.1321

#### Translated

Intro: Bitte denken Sie bei der Beantwortung der folgenden Fragen an die letzten 3 Monate/ 4 Wochen.  
Text: Meine Arbeit ermöglichte es mir, Initiative zu übernehmen.  
Scale:  

- 1 = trifft überhaupt nicht zu
- ...
- 7 = trifft voll und ganz zu

Translation: Stegmann, S., van Dick, R., Ullrich, J., Charalambous, J., Menzel, B., Egold, N., & Wu, T. T.-C. (2010). Der Work Design Questionnaire. Zeitschrift Für Arbeits- Und Organisationspsychologie A&O, 54, 1 -28. https://doi.org/10.1026/0932-4089/a000002

#### Measured At

| MP   | TP    | MP                    | TP    | MP   | TP    | MP   | TP    | MP   | TP    | MP   | TP    |
|------|-------|-----------------------|-------|------|-------|------|-------|------|-------|------|-------|
| T1   | 12/19 |                       |       | T12  | 01/21 | T24  | 01/22 |      |       | T43  | 01/24 |
|      |       |                       |       | T13  | 02/21 | T25  | 02/22 |      |       | T44  | 02/24 |
|      |       | <strong>T2</strong>   | 03/20 | T14  | 03/21 | T26  | 03/22 |      |       | T45  | 03/24 |
|      |       | <strong>T3</strong>   | 04/20 | T15  | 04/21 | T27  | 04/22 |      |       | T46  | 04/24 |
|      |       | <strong>T4</strong>   | 05/20 | T16  | 05/21 | T28  | 05/22 |      |       | T47  | 05/24 |
|      |       | <strong>T5</strong>   | 06/20 | T17  | 06/21 | T29  | 06/22 | T36  | 06/23 | T48  | 06/24 |
|      |       | <strong>T6</strong>   | 07/20 | T18  | 07/21 | T30  | 07/22 | T37  | 07/23 | T49  | 07/24 |
|      |       | <strong>T7</strong>   | 08/20 | T19  | 08/21 | T31  | 08/22 | T38  | 08/23 | T50  | 08/24 |
|      |       | <strong>T8</strong>   | 09/20 | T20  | 09/21 | T32  | 09/22 | T39  | 09/23 | T51  | 09/24 |
|      |       | <strong>T9</strong>   | 10/20 | T21  | 10/21 | T33  | 10/22 | T40  | 10/23 | T52  | 10/24 |
|      |       | <strong>T10</strong>  | 11/20 | T22  | 11/21 | T34  | 11/22 | T41  | 11/23 | T53  | 11/24 |
|      |       | <strong>T11</strong>  | 12/20 | T23  | 12/21 | T35  | 12/22 | T42  | 12/23 | T54  | 12/24 |

```{r echo=FALSE}
library(ggplot2)

set.seed(1234)
TPs <- c("T2","T3","T4","T5","T6","T7","T8","T9","T10","T11")
N = sample(800:1700, length(TPs), replace = TRUE)
data = data.frame(TPs = factor(TPs, levels = TPs, ordered = TRUE), N)

ggplot(data, aes(TPs, N)) + 
  theme_minimal() + 
  geom_bar(stat = "identity", color = "#B02F2C", fill = "#B02F2C") + 
  labs(x = "Measurement Occasion", y = "Observations")
```





</div><!--Second Column -->

## Two Constructs {-}  
</div><!--"Row"-->